apiVersion: skaffold/v3
kind: Config
metadata:
  name: consul-k8s
build:
  # This bit is temporary until https://github.com/GoogleContainerTools/skaffold/issues/7992 is resolved
  # and image copying works again
  insecureRegistries:
    - "dstoughhashicorp"  #
# Consider a different tagging policy to eliminate image rebuilds
  artifacts:
  - image: consul
    context: .
    custom:
      buildCommand: |
        CONSUL_DEV_IMAGE=$IMAGE make dev-docker
      dependencies:
#          dockerfile:  # This doesn't work because our dockerfile is not a self-contained build
#            path: ./build-support/docker/Consul-Dev.dockerfile
#            buildArgs:
#              CONSUL_IMAGE_VERSION: latest
        paths:
        - ./agent/**/*.go
        - ./acl/**/*.go
        - ./command/**/*.go
        - ./connect/**/*.go
        - ./lib/**/*.go
        ignore:
        - ./**/*_test.go
#    - image: hashicorp/consul-k8s-control-plane
#      context: ./consul-k8s/control-plane
#      docker:
#        dockerfile: ./consul-k8s/control-plane/Dockerfile
#        target: dev
  local:
    useBuildkit: true
    concurrency: 0
    push: true
# manifests:
#   helm:
#     releases:
#     - name: consul-dev
#       chartPath: ./consul-k8s/charts/consul
#       setValueTemplates:
#         global.image: '{{.IMAGE_NAME}}:{{.IMAGE_TAG}}'
#         # global.imageK8S: '{{.IMAGE_NAME2}}:{{.IMAGE_TAG2}}@{{.IMAGE_DIGEST2}}'
deploy:
  helm:
    releases:
    - name: consul-dev
      chartPath: ./consul-k8s/charts/consul
      setValueTemplates:
        global.image: '{{.IMAGE_REPO}}:{{.IMAGE_TAG}}'
        # global.image: '{{.IMAGE_NAME}}:{{.IMAGE_TAG}}' # This would be the name without using the registry
        # global.imageK8S: '{{.IMAGE_NAME2}}:{{.IMAGE_TAG2}}@{{.IMAGE_DIGEST2}}'

# TODO port forward the UI
#portForward:
#  - resourceType: service
#    resourceName: consul-ui # TODO: fix
#    port: 8000              # TODO: fix
#    localPort: 8080         # TODO: fix
