name: go-tests

on: 
  push:
    branches-ignore:
      - stable-website
      - 'docs/**'
      - 'ui/**'
      - 'mktg-**' # Digital Team Terraform-generated branches' prefix
      - 'backport/docs/**'
      - 'backport/ui/**'
      - 'backport/mktg-**'
  
permissions:
  contents: read

env:
  TEST_RESULTS: /tmp/test-results
  GOTESTSUM_VERSION: 1.8.2

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      compute-standard: ${{ steps.setup-outputs.outputs.compute-standard }}
      compute-larger: ${{ steps.setup-outputs.outputs.compute-larger }}
      compute-arm64: ${{ steps.setup-outputs.outputs.compute-arm64 }}
    steps:
    - id: setup-outputs
      name: Setup outputs
      run: |
          echo 'compute-standard=["custom", "linux", "small"]' >> $GITHUB_OUTPUT
          echo 'compute-larger=["custom", "linux", "medium"]' >> $GITHUB_OUTPUT
          echo 'compute-arm64=["self-hosted", "ondemand", "os=macos-arm", "arm64"]' >> $GITHUB_OUTPUT
  check-go-mod:
    needs: 
    - setup
    uses: ./.github/workflows/reusable-check-go-mod.yml
  check-generated-protobuf:
    needs: 
    - setup   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
      with:
        go-version-file: 'go.mod'
    - run: make proto-tools
      name: Install protobuf
    - run: make proto-format
      name: "Protobuf Format"
    - run: make --always-make proto
    - run: |
            if ! git diff --exit-code; then
              echo "Generated code was not updated correctly"
              exit 1
            fi
    - run: make proto-lint
      name: "Protobuf Lint"
    - name: Notify Slack
      if: failure()
      run: .github/scripts/notify_slack.sh 
  check-generated-deep-copy:
    needs: 
    - setup   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
      with:
        go-version-file: 'go.mod'
    - run: make codegen-tools
      name: Install deep-copy
    - run: make --always-make deep-copy
    - run: |
        if ! git diff --exit-code; then
          echo "Generated code was not updated correctly"
          exit 1
        fi
    - name: Notify Slack
      if: failure()
      run: .github/scripts/notify_slack.sh  
  lint-enums:
    needs: 
    - setup   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
      with:
        go-version-file: 'go.mod'
    - run: go install github.com/reillywatson/enumcover/cmd/enumcover@master && enumcover ./...   
    - name: Notify Slack
      if: failure()
      run: .github/scripts/notify_slack.sh

  lint-container-test-deps:
    needs: 
    - setup   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
      with:
        go-version-file: 'go.mod'
    - run: make lint-container-test-deps 
    - name: Notify Slack
      if: failure()
      run: .github/scripts/notify_slack.sh

  lint-consul-retry:
    needs: 
    - setup   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
      with:
        go-version-file: 'go.mod'
    - run: go install github.com/hashicorp/lint-consul-retry@master && lint-consul-retry
    - name: Notify Slack
      if: failure()
      run: .github/scripts/notify_slack.sh

  lint:
    needs: 
    - setup   
    uses: ./.github/workflows/reusable-lint.yml

  lint-32bit:
    needs: 
    - setup   
    uses: ./.github/workflows/reusable-lint.yml
    with:
      go-arch: "386"

  # create a development build
  dev-build:
    needs: 
    - setup   
    uses: ./.github/workflows/reusable-dev-build.yml

  # create a development build for arm64
  dev-build-arm64:
    needs: 
    - setup   
    uses: ./.github/workflows/reusable-dev-build.yml
    with:
      uploaded-binary-name: 'consul-bin-arm64'
      # runs-on: ${{ needs.setup.outputs.compute-arm64 }}

  go-test-arm64:
    # TODO(JM):  Fix to run on arm64
    needs: 
    - setup   
    - dev-build-arm64
    uses: ./.github/workflows/reusable-unit.yml
    with:
      directory: .
      go-version: "1.20"
      uploaded-binary-name: 'consul-bin-arm64'
      # runs-on: ${{ needs.setup.outputs.compute-arm64 }}
    # steps:
    #   - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    #   - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
    #     with:
    #       go-version-file: 'go.mod'
    #   - name: Install gotestsum
    #     run: |
    #       wget https://github.com/gotestyourself/gotestsum/releases/download/v${{env.GOTESTSUM_VERSION}}/gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
    #       sudo tar -C /usr/local/bin -xzf gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
    #       rm gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
    #   - run: go mod download
    #   - name: make dev
    #     run: |
    #       # TODO(JM)- figure out why this is only needed on these branches
    #       # if [[ '${{ github.ref }}' == 'refs/heads/main' || startsWith('${{ github.ref }}', 'refs/heads/release/') ]]; then
    #         make dev
    #       # fi
    #   # TODO(JM)- if not always building above, re-enable this.
    #   # - uses: actions/download-artifact@v3
    #   #   with:
    #   #     name: consul-bin
    #   #     path: ./bin/consul
    #   - run: go mod download
    #   - name: go test
    #     run: |
    #         PACKAGE_NAMES=$(go list ./...)
            
    #         # TODO(JM): figure out why this erroring
    #         # if [[ github.ref == 'refs/heads/main' || !startsWith(github.ref, 'refs/heads/release/') ]]; then
    #         #   export GO_TEST_FLAGS="-short"
    #         # fi
            
    #         # some tests expect this umask, and arm images have a different default
    #         umask 0022

    #         gotestsum \
    #         --format=short-verbose \
    #         --jsonfile /tmp/jsonfile/go-test-${CIRCLE_NODE_INDEX}.log \
    #         --debug \
    #         --rerun-fails=3 \
    #         --rerun-fails-max-failures=40 \
    #         --rerun-fails-report=/tmp/gotestsum-rerun-fails \
    #         --packages="$PACKAGE_NAMES" \              
    #         --junitfile ${{env.TEST_RESULTS}}/gotestsum-report.xml -- \
    #         -tags="$GOTAGS" -p 4 \
    #         ${GO_TEST_FLAGS-} \
    #         -cover -coverprofile=coverage.txt
    #   - uses: actions/upload-artifact@master
    #     with:
    #       name: test-results
    #       path: ${{env.TEST_RESULTS}}
    #   - uses: actions/upload-artifact@master
    #     with:
    #       name: jsonfile
    #       path: /tmp/jsonfile
    #   # - name: "Re-run fails report"
    #   #   run: |
    #   #     #!/usr/bin/env bash
    #   #     #
    #   #     # Add a comment on the github PR if there were any rerun tests.
    #   #     #
    #   #     set -eu -o pipefail

    #   #     report_filename="${1?report filename is required}"
    #   #     if [ ! -s "$report_filename" ]; then
    #   #         echo "gotestsum rerun report file is empty or missing"
    #   #         exit 0
    #   #     fi

    #   #     function report {
    #   #         echo ":repeat: gotestsum re-ran some tests in $CIRCLE_BUILD_URL"
    #   #         echo
    #   #         echo '```'
    #   #         cat "$report_filename"
    #   #         echo '```'
    #   #     }

    #   #     report
    #   - name: Notify Slack
    #     if: failure()
    #     run: .github/scripts/notify_slack.sh

  go-test:
    needs: 
    - setup   
    - dev-build
    uses: ./.github/workflows/reusable-unit.yml
    with:
      directory: .
      go-version: "1.20"
    # TODO(JM): Combine with go-test-arm64
    # steps:
    #   - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    #   - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
    #     with:
    #       go-version-file: 'go.mod'
    #   - name: Setup go mod cache
    #     uses: actions/cache@v3
    #     with:
    #       path: |
    #         ~/.cache/go-build
    #         ~/go/pkg/mod
    #       key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    #       restore-keys: |
    #         ${{ runner.os }}-go-

    #   - name: Install gotestsum
    #     run: |
    #       wget https://github.com/gotestyourself/gotestsum/releases/download/v${{env.GOTESTSUM_VERSION}}/gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
    #       sudo tar -C /usr/local/bin -xzf gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
    #       rm gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz

    #   - run:  mkdir -p ${{env.TEST_RESULTS}}
    #   # - name: Download consul
    #   #   run: |
    #   #     mkdir -p $HOME/bin
    #   #     container_id=$(docker create ${{env.CONSUL_OSS_DOCKER_IMAGE}})
    #   #     docker cp "$container_id:/bin/consul" $HOME/bin/consul
    #   #     docker rm "$container_id"
    #   - name: Run go tests
    #     run: |
    #         PACKAGE_NAMES=$(go list ./...)
            
    #         # TODO(JM): figure out why this erroring
    #         # if [[ github.ref == 'refs/heads/main' || !startsWith(github.ref, 'refs/heads/release/') ]]; then
    #         #   export GO_TEST_FLAGS="-short"
    #         # fi
            
    #         # some tests expect this umask, and arm images have a different default
    #         umask 0022

    #         gotestsum \
    #         --format=short-verbose \
    #         --jsonfile /tmp/jsonfile/go-test-${CIRCLE_NODE_INDEX}.log \
    #         --debug \
    #         --rerun-fails=3 \
    #         --rerun-fails-max-failures=40 \
    #         --rerun-fails-report=/tmp/gotestsum-rerun-fails \
    #         --packages="$PACKAGE_NAMES" \              
    #         --junitfile ${{env.TEST_RESULTS}}/gotestsum-report.xml -- \
    #         -tags="$GOTAGS" -p 4 \
    #         ${GO_TEST_FLAGS-} \
    #         -cover -coverprofile=coverage.txt
    #   - uses: actions/upload-artifact@master
    #     with:
    #       name: test-results
    #       path: ${{env.TEST_RESULTS}}
    #   - uses: actions/upload-artifact@master
    #     with:
    #       name: jsonfile
    #       path: /tmp/jsonfile
    #   # - name: "Re-run fails report"
    #   #   run: |
    #   #     #!/usr/bin/env bash
    #   #     #
    #   #     # Add a comment on the github PR if there were any rerun tests.
    #   #     #
    #   #     set -eu -o pipefail

    #   #     report_filename="${1?report filename is required}"
    #   #     if [ ! -s "$report_filename" ]; then
    #   #         echo "gotestsum rerun report file is empty or missing"
    #   #         exit 0
    #   #     fi

    #   #     function report {
    #   #         echo ":repeat: gotestsum re-ran some tests in $CIRCLE_BUILD_URL"
    #   #         echo
    #   #         echo '```'
    #   #         cat "$report_filename"
    #   #         echo '```'
    #   #     }

    #   #     report 
    #   - name: Notify Slack
    #     if: failure()
    #     run: .github/scripts/notify_slack.sh

  go-test-envoyextensions:
    needs: 
    - setup   
    - dev-build
    uses: ./.github/workflows/reusable-unit.yml
    with:
      directory: envoyextensions
      go-version: "1.20"

  go-test-troubleshoot:
    needs: 
    - setup   
    - dev-build
    uses: ./.github/workflows/reusable-unit.yml
    with:
      directory: troubleshoot
      go-version: "1.20"

  go-test-api-1-19:
    needs: 
    - setup   
    - dev-build
    uses: ./.github/workflows/reusable-unit.yml
    with:
      directory: api
      go-version: "1.19"

  go-test-api-1-20:
    needs: 
    - setup   
    - dev-build
    uses: ./.github/workflows/reusable-unit.yml
    with:
      directory: api
      go-version: "1.20"

  go-test-sdk-1-19:
    needs: 
    - setup   
    - dev-build
    uses: ./.github/workflows/reusable-unit.yml
    with:
      directory: sdk
      go-version: "1.19"

  go-test-sdk-1-20:
    needs: 
    - setup   
    - dev-build
    uses: ./.github/workflows/reusable-unit.yml
    with:
      directory: sdk
      go-version: "1.20"

  noop:
    runs-on: ubuntu-latest
    steps:
      - run: "echo ok"
