name: go-tests

on: [push]
  
permissions:
  contents: read

jobs:
  check-go-mod:
    uses: ./.github/workflows/reusable-check-go-mod.yml
    if: |
        github.ref != 'stable-website' || 
        !startsWith(github.ref, 'refs/heads/docs/')
