name: go-tests

on: [push]
  
permissions:
  contents: read

jobs:
  get-go-version:
    name: "Determine Go toolchain version"
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Determine Go version
        id: get-go-version
        # We use .go-version as our source of truth for current Go
        # version, because "goenv" can react to it automatically.
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "::set-output name=go-version::$(cat .go-version)"
  check-go-mod:  #TODO(JM): figure out how to get around no anchors
    if: |
        github.ref != 'stable-website' || 
        !startsWith(github.ref, 'refs/heads/docs/') || 
        !startsWith(github.ref, 'refs/heads/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/docs/') || 
        !startsWith(github.ref, 'refs/heads/backport/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/mktg-.')
    uses: ./.github/workflows/reusable-check-go-mod.yml

  check-generated-protobuf:
    if: |
        github.ref != 'stable-website' || 
        !startsWith(github.ref, 'refs/heads/docs/') || 
        !startsWith(github.ref, 'refs/heads/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/docs/') || 
        !startsWith(github.ref, 'refs/heads/backport/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/mktg-.')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    #TODO(JM): figure out how to give these names
    - run: make proto-tools
      name: Install protobuf
    - run: make proto-format
      name: "Protobuf Format"
    - run: make --always-make proto
    - run: |
            if ! git diff --exit-code; then
              echo "Generated code was not updated correctly"
              exit 1
            fi
    - run: make proto-lint
      name: "Protobuf Lint"
  
  check-generated-deep-copy:
    if: |
        github.ref != 'stable-website' || 
        !startsWith(github.ref, 'refs/heads/docs/') || 
        !startsWith(github.ref, 'refs/heads/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/docs/') || 
        !startsWith(github.ref, 'refs/heads/backport/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/mktg-.')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    - run: make codegen-tools
      name: Install deep-copy
    - run: make --always-make deep-copy
    - run: |
        if ! git diff --exit-code; then
          echo "Generated code was not updated correctly"
          exit 1
        fi
  
  lint-enums:
    if: |
        github.ref != 'stable-website' || 
        !startsWith(github.ref, 'refs/heads/docs/') || 
        !startsWith(github.ref, 'refs/heads/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/docs/') || 
        !startsWith(github.ref, 'refs/heads/backport/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/mktg-.')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    - run: go install github.com/reillywatson/enumcover/cmd/enumcover@master && enumcover ./...   
    #TODO(JM) - get this from Dan
    # - run: *notify-slack-failure

  lint-container-test-deps:
    if: |
        github.ref != 'stable-website' || 
        !startsWith(github.ref, 'refs/heads/docs/') || 
        !startsWith(github.ref, 'refs/heads/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/docs/') || 
        !startsWith(github.ref, 'refs/heads/backport/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/mktg-.')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    - run: make lint-container-test-deps 
    #TODO(JM) - get this from Dan
    # - run: *notify-slack-failure

  lint-consul-retry:
    if: |
        github.ref != 'stable-website' || 
        !startsWith(github.ref, 'refs/heads/docs/') || 
        !startsWith(github.ref, 'refs/heads/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/docs/') || 
        !startsWith(github.ref, 'refs/heads/backport/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/mktg-.')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
    - run: go install github.com/hashicorp/lint-consul-retry@master && lint-consul-retry
    #TODO(JM) - get this from Dan
    # - run: *notify-slack-failure 

  lint:
    if: |
        github.ref != 'stable-website' || 
        !startsWith(github.ref, 'refs/heads/docs/') || 
        !startsWith(github.ref, 'refs/heads/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/docs/') || 
        !startsWith(github.ref, 'refs/heads/backport/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/mktg-.')
    uses: ./.github/workflows/reusable-lint.yml

  lint-32bit:
    if: |
        github.ref != 'stable-website' || 
        !startsWith(github.ref, 'refs/heads/docs/') || 
        !startsWith(github.ref, 'refs/heads/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/docs/') || 
        !startsWith(github.ref, 'refs/heads/backport/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/mktg-.')
    uses: ./.github/workflows/reusable-lint.yml
    with:
      go-arch: "386"

