name: reusable-unit 

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      go-version:
        required: true
        type: string

# Environment variables can only be used at the step level
env:
  TEST_RESULTS: /tmp/test-results # path to where test results are saved
  GOTESTSUM_VERSION: 1.8.2

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
        with:
          go-version-file: 'go.mod'
      - name: Setup go mod cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install gotestsum
        run: |
          wget https://github.com/gotestyourself/gotestsum/releases/download/v${{env.GOTESTSUM_VERSION}}/gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
          sudo tar -C /usr/local/bin -xzf gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
          rm gotestsum_${{env.GOTESTSUM_VERSION}}_linux_amd64.tar.gz
      - run: mkdir -p ${{env.TEST_RESULTS}}
      - name: go mod download
        working-directory: ${{inputs.directory}}
        run: go mod download
      - name: Make directory for consul bin
        run: mkdir ./${{inputs.directory}}/bin
      - uses: actions/download-artifact@master
        with:
          name: consul-bin
          path: ./${{inputs.directory}}/bin
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./${{inputs.directory}}/bin
      - name: Run tests 
        working-directory: ${{inputs.directory}}
        run: |
          export PATH=$PATH:/home/runner/work/consul/consul/${{inputs.directory}}/bin
          echo "PATH: $PATH"
          gotestsum --format=testname --junitfile ${{env.TEST_RESULTS}}/gotestsum-report.xml ./... -- -p
      - name: Notify Slack
        if: failure()
        run: .github/scripts/notify_slack.sh
