name: reusable-dev-build 

on:
  workflow_call:
    inputs:
      uploaded-binary-name:
        required: false
        type: string
        default: "consul-bin"  
jobs:
  dev-build:
    if: |
        github.ref != 'refs/heads/stable-website' || 
        !startsWith(github.ref, 'refs/heads/docs/') || 
        !startsWith(github.ref, 'refs/heads/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/docs/') || 
        !startsWith(github.ref, 'refs/heads/backport/ui/') || 
        !startsWith(github.ref, 'refs/heads/backport/mktg-.')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3.3.0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@v3.5.0
        with:
          go-version-file: 'go.mod'
        # TODO(JM) - figure out why this fails and if it is needed
      # # this normally runs as the first job and has nothing to attach; only used in main branch after rebuilding UI
      # - uses: actions/download-artifact@v3
      #   with:
      #     name: root-path
      #     path: .
      - name: Build
        run: make dev
      # save dev build to pass to downstream jobs
      - uses: actions/upload-artifact@master
        with:
          name: ${{inputs.uploaded-binary-name}}
          path: ./bin/consul
      - name: Notify Slack
        if: failure()
        run: .github/scripts/notify_slack.sh
