name: Run smoke tests against CI-built artifacts

on:
  workflow_run:
    workflows: ["build"]
    types:
      - on-success

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "success"
