name: test CI-built artifacts

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches: [ 
      "main",
      "gha-basic-artifact-validation"
    ]

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_conclusion: success
      - run: ls -la