name: test CI-built artifacts

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches: [ 
      "main",
      "gha-basic-artifact-validation"
    ]

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo ref ${{ github.ref }}
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          allowed-conclusions: success
      - run: echo job build has succeeded! 
  